import arcade

DIO_CHARACTER = {
    "display_name": "DIO",
    "file_prefix": "DIO",
    "health": 500,
    "stand_name": "The World",
    "frame_ranges": {
        "idle": (0, 37),
        "move_right": (54, 69),
        "move_left": (70, 85),
        "jump": (103, 115),
        "crouch": (42, 49),
        "dash_forward": (86, 93),
        "dash_backward": (94, 101),
        "stand_summon": (129, 137),
        "attack1": (371, 375),
        "attack2": (376, 386),
        "attack3": (387, 398),
        "stand_attack1": (608, 609),
        "stand_attack2": (608, 609),
        "stand_attack3": (608, 609),
    },
    "jump_loop": (111, 112),
    "dash_forward_loop": (88, 91),
    "dash_backward_loop": (96, 99),
    "animation_speeds": {
        "idle": 6,
        "move_right": 5,
        "move_left": 5,
        "jump": 3,
        "crouch": 5,
        "dash_forward": 4,
        "dash_backward": 4,
        "stand_summon": 5,
        "attack1": 3,
        "attack2": 3,
        "attack3": 4,
        "stand_attack1": 3,
        "stand_attack2": 3,
        "stand_attack3": 4,
    },
    "attacks": {
        "attack1": {
            "damage": 10,
            "knockback": 5,
            "hitbox": (50, 80),
            "offset_x": 60,
            "active_frames": (372, 372),
        },
        "attack2": {
            "damage": 12,
            "knockback": 8,
            "hitbox": (60, 80),
            "offset_x": 65,
            "active_frames": (379, 380),
        },
        "attack3": {
            "damage": 25,
            "knockback": 20,
            "hitbox": (70, 90),
            "offset_x": 70,
            "active_frames": (390, 391),
        },
        "stand_attack1": {
            "damage": 15,
            "knockback": 10,
            "hitbox": (70, 100),
            "offset_x": 10,
            "active_frames": (140, 142),
        },
        "stand_attack2": {
            "damage": 18,
            "knockback": 12,
            "hitbox": (80, 100),
            "offset_x": 85,
            "active_frames": (169, 170),
        },
        "stand_attack3": {
            "damage": 30,
            "knockback": 25,
            "hitbox": (90, 110),
            "offset_x": 90,
            "active_frames": (180, 181),
        },
    },
    "combo_window": 30,
    "crouch_freeze_frame": 45,
    "animation_speed": 5,
    "movement_speed": 2,
    "jump_speed": 15,
    "dash_speed": 15,
    "dash_distance": 220,
    "dash_cooldown": 40,
    "sprite_scale": 2,
    "color": arcade.color.YELLOW
}

DIO_STAND = {
    "display_name": "The World",
    "folder_name": "TheWorld",
    "file_prefix": "TheWorld",
    "frame_ranges": {
        "idle": (0, 4),
        "move_forward": (23, 24),
        "move_backward": (17, 18),
        "jump": (38, 39),
        "dash_forward": (27, 31),
        "dash_backward": (33, 37),
        "summon": (40, 45),
        "attack1": (142, 149),
        "attack2": (165, 175),
        "attack3": (176, 184),
    },
    "jump_loop": (38, 39),
    "dash_forward_loop": (28, 29),
    "dash_backward_loop": (34, 35),
    "animation_speeds": {
        "idle": 7,
        "move_forward": 4,
        "move_backward": 4,
        "jump": 3,
        "dash_forward": 9,
        "dash_backward": 7,
        "summon": 6,
        "attack1": 4,
        "attack2": 4,
        "attack3": 5,
    },
    "sprite_scale": 2,
    "offset_x": 0,
    "offset_y": 0,
    "color": arcade.color.GOLD
}