import arcade

JOTARO_CHARACTER = {
    "display_name": "Jotaro Kujo",
    "file_prefix": "Jot",
    "health": 1000,
    "stand_name": "Star Platinum",
    "hitbox_size": (80, 200),
    "block_frames": (688, 694),
    "block_offset_x": 40,
    "block_offset_y": 0,
    "block_duration": 30,
    "block_cooldown": 40,

    # ПАРАМЕТРЫ ШКАЛЫ СТЕНДА
    "stand_meter_max": 100,
    "stand_summon_cost": 10,
    "stand_block_drain": 20,
    "stand_block_drain_no_stand": 10,
    "stand_gain_on_hit": 15,
    "stand_gain_on_block": 5,
    "stand_gain_on_attack": 2,
    "stand_passive_gain": 0.1,
    "stand_damage_drain": 15,
    "stand_damage_drain_no_stand": 5,

    # ОПТИМИЗИРОВАННЫЙ СЛОВАРЬ АНИМАЦИЙ
    "animations": {
        "idle": ((0, 23), 8),
        "move_right": ((37, 52), 5),
        "move_left": ((53, 68), 5),
        "jump": ((84, 99), 3),
        "crouch": ((26, 36), 5),
        "dash_forward": ((69, 75), 4),
        "dash_backward": ((76, 82), 4),
        "stand_summon": ((125, 136), 3),
        "attack1": ((452, 457), 3),
        "attack2": ((458, 466), 3),
        "attack3": ((467, 476), 4),
        "stand_attack1": ((688, 694), 3),
        "stand_attack2": ((688, 694), 3),
        "stand_attack3": ((153, 160), 4),
        "intro": ((0, 37), 6),
        "victory": ((526, 576), 5),
        "defeat": ((323, 341), 5),
        "hit": ((170, 173), 3),  # Анимация получения урона
    },

    "jump_loop": (94, 95),
    "dash_forward_loop": (71, 73),
    "dash_backward_loop": (78, 80),

    "attacks": {
        "attack1": {
            "damage": 15,
            "knockback": 5,
            "hitbox": (50, 75),
            "offset_x": 85,
            "offset_y": 10,
            "active_frames": (453, 454),
        },
        "attack2": {
            "damage": 20,
            "knockback": 8,
            "hitbox": (50, 50),
            "offset_x": 130,
            "offset_y": -70,
            "active_frames": (461, 461),
        },
        "attack3": {
            "damage": 50,
            "knockback": 18,
            "hitbox": (65, 85),
            "offset_x": 110,
            "offset_y": 45,
            "active_frames": (470, 470),
        },
        "stand_attack1": {
            "damage": 12,
            "knockback": 10,
            "hitbox": (65, 95),
            "offset_x": 130,
            "offset_y": 45,
            "active_frames": (266, 266),
        },
        "stand_attack2": {
            "damage": 15,
            "knockback": 12,
            "hitbox": (75, 95),
            "offset_x": 80,
            "offset_y": 45,
            "active_frames": (287, 287),
        },
        "stand_attack3": {
            "damage": 25,
            "knockback": 22,
            "hitbox": (85, 105),
            "offset_x": 85,
            "offset_y": 45,
            "active_frames": (304, 305),
        },
    },
    "combo_window": 30,
    "crouch_freeze_frame": 31,
    "movement_speed": 3,
    "jump_speed": 15,
    "dash_speed": 15,
    "dash_distance": 250,
    "dash_cooldown": 35,
    "sprite_scale": 2,
    "color": arcade.color.BLUE
}

JOTARO_STAND = {
    "display_name": "Star Platinum",
    "folder_name": "StarPlatinum",
    "file_prefix": "SP",
    "animations": {
        "idle": ((0, 19), 7),
        "block": ((114, 119), 6),
        "move_forward": ((41, 47), 5),
        "move_backward": ((49, 55), 5),
        "jump": ((69, 83), 3),
        "dash_forward": ((56, 62), 6),
        "dash_backward": ((63, 68), 6),
        "summon": ((99, 110), 3),
        "attack1": ((266, 270), 4),
        "attack2": ((282, 293), 4),
        "attack3": ((301, 313), 5),
    },
    "jump_loop": (78, 79),
    "dash_forward_loop": (57, 58),
    "dash_backward_loop": (64, 65),
    "sprite_scale": 2,
    "offset_x": -40,
    "offset_y": 0,
    "color": arcade.color.PURPLE
}